name: CI (Post-Merge Full Suite)

on:
  pull_request:
    types: [closed]

jobs:
  build-test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CHROMA_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RUN_OPENAI_API_TESTS: "1"
      BASE_URL: "https://example.invalid"
      FACEBOOK_USER_AGENT: "facebookexternalua"
      LOG_PSEUDONYM_SECRET: ${{ secrets.LOG_PSEUDONYM_SECRET }}
      META_APP_SECRET: "testsecret"
      META_VERIFY_TOKEN: "verifytoken"
      META_WHATSAPP_TOKEN: "whatsapptoken"
      META_PHONE_NUMBER_ID: "1234567890"
      IN_META_SANDBOX_MODE: "False"
      META_SANDBOX_PHONE_NUMBER: "15555555555"
      BT_SERVANT_LOG_LEVEL: "info"
      DATA_DIR: "./data"
      ENABLE_ADMIN_AUTH: "False"
      ADMIN_API_TOKEN: "admin-token"
      HEALTHCHECK_API_TOKEN: "health-token"
    steps:
      - name: Checkout merge commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff pylint mypy pyright import-linter bandit pip-audit deptry pre-commit
          pip install -e .

      - name: Ensure data dir
        run: mkdir -p data

      - name: Ruff (format check)
        run: ruff format --check bt_servant_engine

      - name: Ruff (lint)
        run: ruff check .

      - name: Pylint
        run: pylint -rn -sn $(git ls-files '*.py')

      - name: Mypy
        run: mypy .

      - name: Pyright
        run: pyright

      - name: Import Linter
        run: lint-imports

      - name: Bandit
        run: bandit -q -r bt_servant_engine

      - name: Pip Audit
        run: pip-audit -r requirements.txt

      - name: Deptry
        run: deptry .

      - name: Pytest (full, includes OpenAI tests + coverage)
        run: pytest --maxfail=1 --disable-warnings -q --cov=bt_servant_engine --cov-report=term-missing --cov-fail-under=64
